apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources.yaml

images:
  - name: nginx
    newName: myregistry.io/nginx
    newTag: 1.19.7
  - name: alpine
    newName: myregistry.io/alpine
    newTag: 3.13.2

configurations:
  - images-config.yaml
