apiVersion: v1
data:
  main.conf: ' color=cornflower_blue log_level=info'
kind: ConfigMap
metadata:
  name: conf-4dm5ccb7g8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  template:
    spec:
      containers:
      - image: example:1.0
        name: example
        volumeMounts:
        - mountPath: /etc/config
          name: conf
      volumes:
      - configMap:
          name: conf-4dm5ccb7g8
        name: conf
