kind: Kustomization

resources:
  - ../../base

secretGenerator:
  - name: dbpass
    files:
      - dbpass.txt
  - name: recaptcha
    files:
      - site_key.txt
      - secret_key.txt

patchesStrategicMerge:
  - configmap.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: example
    path: deployment.yaml
