apiVersion: v1
data:
  db.conf: |
    endpoint=127.0.0.1:1234
    name=app
    user=admin
    pass=/var/run/secrets/db/dbpass.txt
  main.conf: ' color=cornflower_blue log_level=info'
  recaptcha.conf: '| enabled=true site_key=/var/run/secrets/recaptcha/site_key.txt secret_key=/var/run/secrets/recaptcha/secret_key.txt'
kind: ConfigMap
metadata:
  annotations: {}
  labels: {}
  name: conf-gccb9hm76t
---
apiVersion: v1
data:
  dbpass.txt: ZGJwYXNzCg==
kind: Secret
metadata:
  name: dbpass-96786m5764
type: Opaque
---
apiVersion: v1
data:
  secret_key.txt: c2VjcmV0a2V5LnR4dAo=
  site_key.txt: c2l0ZWtleS50eHQK
kind: Secret
metadata:
  name: recaptcha-9hdb6btf9b
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  template:
    spec:
      containers:
      - image: example:1.0
        name: example
        volumeMounts:
        - mountPath: /var/run/secrets/recaptcha/
          name: recaptcha
        - mountPath: /var/run/secrets/db/
          name: dbpass
        - mountPath: /etc/config
          name: conf
      volumes:
      - name: recaptcha
        secret:
          secretName: recaptcha-9hdb6btf9b
      - name: dbpass
        secret:
          secretName: dbpass-96786m5764
      - configMap:
          name: conf-gccb9hm76t
        name: conf
